name: mlenv_cuda12
channels:
  - pytorch-nightly
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - abseil-cpp=20230802.0=h6a678d5_2
  - absl-py=1.4.0=py311h06a4308_0
  - aiohttp=3.8.5=py311h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - aom=3.6.1=h59595ed_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-timeout=4.0.2=py311h06a4308_0
  - attrs=23.1.0=py311h06a4308_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=2.116=mkl
  - blas-devel=3.9.0=16_linux64_mkl
  - blinker=1.6.2=py311h06a4308_0
  - boltons=23.0.0=pyhd8ed1ab_0
  - brotli-python=1.1.0=py311hb755f60_1
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.20.1=hd590300_0
  - ca-certificates=2023.08.22=h06a4308_0
  - cachetools=4.2.2=pyhd3eb1b0_0
  - cairo=1.18.0=h3faef2a_0
  - certifi=2023.7.22=py311h06a4308_0
  - cffi=1.16.0=py311hb3a22ac_0
  - cftime=1.6.2=py311hbed6279_0
  - charset-normalizer=3.3.0=pyhd8ed1ab_0
  - click=8.1.7=py311h06a4308_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.2=py311h06a4308_0
  - conda=23.9.0=py311h38be061_0
  - conda-content-trust=0.2.0=pyhd8ed1ab_0
  - conda-libmamba-solver=23.9.2=pyhd8ed1ab_0
  - conda-package-handling=2.2.0=pyh38be061_0
  - conda-package-streaming=0.9.0=pyhd8ed1ab_0
  - cryptography=41.0.4=py311h63ff55d_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.3.52=0
  - cuda-runtime=12.1.0=0
  - dav1d=1.2.1=hd590300_0
  - debugpy=1.6.7=py311h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.5.0=hcb278e6_1
  - ffmpeg=6.0.0=gpl_h334edf3_105
  - filelock=3.12.4=pyhd8ed1ab_0
  - fmt=10.1.1=h00ab1b0_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.12.1=h267a509_2
  - fribidi=1.0.10=h36c2ea0_0
  - frozenlist=1.3.3=py311h5eee18b_0
  - gettext=0.21.1=h27087fc_0
  - giflib=5.2.1=h5eee18b_3
  - gmp=6.2.1=h58526e2_0
  - gmpy2=2.1.2=py311h6a5fa03_1
  - gnutls=3.7.8=hf3e180e_0
  - google-auth=2.6.0=pyhd3eb1b0_0
  - google-auth-oauthlib=0.5.2=py311h06a4308_0
  - graphite2=1.3.13=h58526e2_1001
  - grpc-cpp=1.48.2=he1ff14a_3
  - grpcio=1.48.2=py311he1ff14a_3
  - gtest=1.14.0=hdb19cb5_0
  - harfbuzz=8.2.1=h3d44ed6_0
  - hdf4=4.2.13=h3ca952b_2
  - hdf5=1.12.1=h2b7332f_3
  - icu=73.2=h59595ed_0
  - idna=3.4=pyhd8ed1ab_0
  - ipykernel=6.25.0=py311h92b7b1e_0
  - ipython=8.15.0=py311h06a4308_0
  - jedi=0.18.1=py311h06a4308_1
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.3.2=pyhd8ed1ab_0
  - jpeg=9e=h5eee18b_1
  - jsonpatch=1.33=pyhd8ed1ab_0
  - jsonpointer=2.4=py311h38be061_3
  - jupyter_client=8.1.0=py311h06a4308_0
  - jupyter_core=5.3.0=py311h06a4308_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.2=h659d440_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libarchive=3.7.2=h039dbb9_0
  - libass=0.17.1=h8fe9dca_1
  - libblas=3.9.0=16_linux64_mkl
  - libcblas=3.9.0=16_linux64_mkl
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.8.0.34=0
  - libcurand=10.3.4.52=0
  - libcurl=8.4.0=hca28451_0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.19=hd590300_0
  - libdrm=2.4.114=h166bdaf_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h807b86a_2
  - libgfortran-ng=13.2.0=h69a702a_2
  - libgfortran5=13.2.0=ha4646dd_2
  - libglib=2.78.0=hebfc3b9_0
  - libhwloc=2.9.3=default_h554bfaf_1009
  - libiconv=1.17=h166bdaf_0
  - libidn2=2.3.4=h166bdaf_0
  - liblapack=3.9.0=16_linux64_mkl
  - liblapacke=3.9.0=16_linux64_mkl
  - libmamba=1.5.2=had39da4_0
  - libmambapy=1.5.2=py311hf2555c7_0
  - libnetcdf=4.8.1=h14805e7_4
  - libnghttp2=1.52.0=h61bc06f_0
  - libnpp=12.0.2.50=0
  - libnsl=2.0.1=hd590300_0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libopus=1.3.1=h7f98852_1
  - libpciaccess=0.17=h166bdaf_0
  - libpng=1.6.39=h753d276_0
  - libprotobuf=3.20.3=he621ea3_0
  - libsodium=1.0.18=h7b6447c_0
  - libsolv=0.7.25=hfc55251_0
  - libsqlite=3.43.2=h2797004_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-ng=13.2.0=h7e041cc_2
  - libtasn1=4.19.0=h166bdaf_0
  - libtiff=4.2.0=hecacb30_2
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.38.1=h0b41bf4_0
  - libva=2.20.0=hd590300_0
  - libvpx=1.13.1=h59595ed_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libxml2=2.11.5=h232c23b_1
  - libzip=1.8.0=h6ac8c49_1
  - libzlib=1.2.13=hd590300_5
  - llvm-openmp=15.0.7=h0cdce71_0
  - lz4-c=1.9.4=hcb278e6_0
  - lzo=2.10=h516909a_1000
  - markdown=3.4.1=py311h06a4308_0
  - markupsafe=2.1.3=py311h459d7ec_1
  - matplotlib-inline=0.1.6=py311h06a4308_0
  - mkl=2022.1.0=h84fe81f_915
  - mkl-devel=2022.1.0=ha770c72_916
  - mkl-include=2022.1.0=h84fe81f_915
  - mpc=1.3.1=hfe3b2da_0
  - mpfr=4.2.0=hb012696_0
  - mpmath=1.3.0=pyhd8ed1ab_0
  - multidict=6.0.2=py311h5eee18b_0
  - ncurses=6.4=hcb278e6_0
  - nest-asyncio=1.5.6=py311h06a4308_0
  - netcdf4=1.6.2=py311h0e679e6_0
  - nettle=3.8.1=hc379101_1
  - networkx=3.2=pyhd8ed1ab_1
  - numpy=1.26.0=py311h64a7726_0
  - oauthlib=3.2.2=py311h06a4308_0
  - openh264=2.3.1=hcb278e6_2
  - openssl=3.1.3=hd590300_0
  - p11-kit=0.24.1=hc5aa10d_0
  - packaging=23.2=pyhd8ed1ab_0
  - pandas=2.1.1=py311h320fe9a_1
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre2=10.40=hc3806b6_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.4.0=py311h6a678d5_1
  - pip=23.3=pyhd8ed1ab_0
  - pixman=0.42.2=h59595ed_0
  - platformdirs=3.10.0=py311h06a4308_0
  - plotly=5.9.0=py311h06a4308_0
  - pluggy=1.3.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.36=py311h06a4308_0
  - protobuf=3.20.3=py311h6a678d5_0
  - psutil=5.9.0=py311h5eee18b_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pybind11-abi=4=hd8ed1ab_3
  - pycosat=0.6.6=py311h459d7ec_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.15.1=py311h06a4308_1
  - pyjwt=2.4.0=py311h06a4308_0
  - pyopenssl=23.2.0=pyhd8ed1ab_1
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.11.6=hab00c5b_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.11=4_cp311
  - pytorch=2.2.0.dev20231019=py3.11_cuda12.1_cudnn8.9.2_0
  - pytorch-cuda=12.1=ha16c6d3_5
  - pytorch-mutex=1.0=cuda
  - pytz=2023.3.post1=pyhd8ed1ab_0
  - pyyaml=6.0.1=py311h459d7ec_1
  - pyzmq=25.1.0=py311h6a678d5_0
  - re2=2022.04.01=h295c915_0
  - readline=8.2=h8228510_1
  - reproc=14.2.4.post0=hd590300_0
  - reproc-cpp=14.2.4.post0=h59595ed_0
  - requests=2.31.0=pyhd8ed1ab_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - ruamel.yaml=0.17.39=py311h459d7ec_0
  - ruamel.yaml.clib=0.2.7=py311h459d7ec_2
  - scikit-learn=1.3.1=py311hc009520_1
  - scipy=1.11.3=py311h64a7726_1
  - setuptools=68.2.2=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - svt-av1=1.7.0=h59595ed_0
  - sympy=1.12=pypyh9d50eac_103
  - tbb=2021.10.0=h00ab1b0_2
  - tenacity=8.2.2=py311h06a4308_0
  - tensorboard=2.12.1=py311h06a4308_0
  - tensorboard-data-server=0.7.0=py311h52d8a92_0
  - tensorboard-plugin-wit=1.6.0=py_0
  - threadpoolctl=3.2.0=pyha21a80b_0
  - tk=8.6.13=h2797004_0
  - torchaudio=2.2.0.dev20231019=py311_cu121
  - torchtriton=2.1.0+6e4932cda8=py311
  - torchvision=0.15.2=cpu_py311h6e929fa_0
  - tornado=6.3.3=py311h5eee18b_0
  - tqdm=4.66.1=pyhd8ed1ab_0
  - traitlets=5.7.1=py311h06a4308_0
  - truststore=0.8.0=pyhd8ed1ab_0
  - typing_extensions=4.8.0=pyha770c72_0
  - tzdata=2023c=h71feb2d_0
  - urllib3=2.0.7=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - werkzeug=2.2.3=py311h06a4308_0
  - wheel=0.41.2=pyhd8ed1ab_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.7=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.4.2=h5eee18b_0
  - yaml=0.2.5=h7f98852_2
  - yaml-cpp=0.8.0=h59595ed_0
  - yarl=1.8.1=py311h5eee18b_0
  - zeromq=4.3.4=h2531618_0
  - zlib=1.2.13=hd590300_5
  - zstandard=0.21.0=py311haa97af0_1
  - zstd=1.5.5=hfc55251_0
prefix: /home/pepa/miniconda3/envs/mlenv_cuda12
